### ISSUE TITLE
HTML Auto complete

### ISSUE THREAD

**Issue by Zyad-Ayad** [vscode-django/vscode-django#128]
I have to Disable this extension every time i want to write some html, Please Fix this.

**Comment by serbboy23** [comment]
Agreed .... this is so frustrating

**Comment by ZeyadMoustafaKamal** [comment]
> I have to Disable this extension every time i want to write some html, Please Fix this.

Put this in your settings.json within .vscode:

  "emmet.includeLanguages": { "django-html": "html" }

**Comment by c-dev-acc1** [comment]
It does not work. I use [this extension](https://github.com/almahdi404/code-django) instead

**Comment by nomad1coder** [comment]
QUICK FIX :  you can create a keyboard shortcut to toggle between languages. Here is mine :

```
[
    {
        "key": "ctrl+k ctrl+k",
        "command": "workbench.action.editor.changeLanguageMode",
        "args": "html",
        "when": "editorLangId == django-html"
    },
    {
        "key": "ctrl+k ctrl+k",
        "command": "workbench.action.editor.changeLanguageMode",
        "args": "django-html",
        "when": "editorLangId == html"
    }
]
```

**Comment by Zyad-Ayad** [comment]
I don't care about this extension anymore and still getting notifications about the issue, I'm closing this.
