### ISSUE TITLE
code snippet should use double quotes (Django recommendation)

### ISSUE THREAD

**Issue by Zerotask** [vscode-django/vscode-django#144]
I noticed when using djlint with the Django profile, that the generated code for the extends code snippet uses single quotes and Django recommends double quotes:

(also noticed it for other tags)

Therefore I suggest the following change:
`extends` -> `{% extends "" %}`
`url` -> `{% url "" %}`
`include` -> `{% include "" %}`

Reference:
https://docs.djangoproject.com/en/4.2/ref/templates/builtins/

**Comment by batisteo** [comment]
Hi Patrick, thanks for the issue and the MR/PR!

For `extends` and `include` I don’t have any problem with it.  
But for `url` and `static`, won’t it be an issue with the double quoted `href="~"`?

What do you think?

**Comment by Zerotask** [comment]
Since you mentioned it, I wasn't so sure about my change :D I just checked it and both works (static with img src and url with a href). This means Django will render those tags first, regardless of the surrounding HTML elements.

**Comment by bblanchon** [comment]
Even if Django renders the nested double quotes correctly, single quotes are less confusing.
Besides, the Django documentation uses single quotes when inside a string.
For example:

```django
{% load static %}
<img src="{% static 'images/hi.jpg' %}" alt="Hi!">
```

Could you adjust the quotes according to the context?

**Comment by batisteo** [comment]
Bonjour Benoît, as far as I know, the extension doesn’t have access to the context (is the cursor is in a double-quoted tag attribute). Also, it’s not excluded that the string may contain a single quote instead of an apostrophe. So I would keep it this way. Wdyt?

**Comment by bblanchon** [comment]
Merci Baptiste.
I was honestly quite surprised when it changed, and I've been "fixing" the quotes because I thought it could cause an issue; that's why I came here.

Are you sure you cannot access the scope? 
It tells that you're in a string and even tells you which quotes it's using.
![Scope](https://github.com/vscode-django/vscode-django/assets/5462433/a83469ff-4b36-4ae5-acbd-6c69ce462c28)
