### ISSUE TITLE
Cursor Navigation

### ISSUE THREAD

**Issue by realimpat** [vscode-django/vscode-django#17]
Installing this extension made it so that auto-indent and soft/hard tab navigation stopped working. 

For example, creating a tag and pressing enter results in 
```
<div>
|
</div>
```

Where it should autoindent like so 
```
<div>
    |
</div>
```

And when I moved cursor down a line and press tab, it doesn't take me back to inner realm of html.

Should be: 
```
                     </thing>
|>                  |

```

But is:
```
                     </thing>
|>  |                 

```

In general, some of the niceties of the default html settings seem to be lost. Minor things that add up. I'll switch back to using this extension if this is fixed!

**Comment by batisteo** [comment]
That’s indeed a pity and a duplicate of #5
