### ISSUE TITLE
"files.associations" settings could be more specific

### ISSUE THREAD

**Issue by cbracco** [vscode-django/vscode-django#28]
Hi there,

When using the "files.associations" settings you suggest in the README, all HTML files are set to "django-html" language by default, which I don't believe is the intended effect. I use the following "files.associations" settings which sets all HTML files to the "html" language mode by default, and then only Django template files as "django-html". Feel free to update your README with these settings suggestions instead, if you'd like.

```
"files.associations": {
    "**/*.html": "html",
    "**/templates/**/*.html": "django-html",
    "**/templates/**/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements"
},
```

Cheers!
Chris

**Comment by batisteo** [comment]
Thanks! :green_heart:

**Comment by cbracco** [comment]
Anytime! 😄

**Comment by aayushbisen** [comment]
Thank you @cbracco 👍
