### ISSUE TITLE
Wrong syntax of a code snippet

### ISSUE THREAD

**Issue by rjsu26** [vscode-django/vscode-django#29]
Issue Type: <b>Bug</b>

in forms.py in Django, type ModelForms and select the code snippet which produces a class. Type the name of the model on both the active cursors. One can see that it becomes:
model=model_name",
Which is inappropriate

Extension version: 0.17.0
VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2187)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.58GB (0.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by felipebastosweb** [comment]
I did created PR #31 for this issue.

**Comment by batisteo** [comment]
Thanks @rjsu26 for reporting, and @felipebastosweb for the fix! :green_heart:

**Comment by rjsu26** [comment]
Thanks for correcting the issue.
