### ISSUE TITLE
Underscores in model snippet causing syntax issue

### ISSUE THREAD

**Issue by dfundako** [vscode-django/vscode-django#32]
The Model snippet produces lines of code with underscores that cause syntax errors. 
Django 2.1.7
Python 3.6.7

To recreate:
In any models.py file:

Type Model and tab to expand snippet and this is produced:

`class (models.Model):`

    class Meta:
        verbose_name = _("")
        verbose_name_plural = _("s")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("_detail", kwargs={"pk": self.pk})

Use "Test" as the model name and migrate:
```
class Test(models.Model):
    class Meta:
        verbose_name = _("test")
        verbose_name_plural = _("tests")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("test_detail", kwargs={"slug": self.slug})
```

```
  File "/home/david/projs/todolist/tracker/models.py", line 8, in Meta
    verbose_name = _("test")
NameError: name '_' is not defined
```

**Comment by batisteo** [comment]
If you’re not interested in translating your project, you can set the setting **Django: I18n** to `false` and then Reload the window.

```json
"django.i18n": false
```

Otherwise, you can import ugettext(_lazy) as underscore. 
```py
from django.utils.translation import ugettext_lazy as _
```
There is a snippet for that btw.

I hope it helps.

**Comment by dfundako** [comment]
Looks great! Thank you for the help!
