### ISSUE TITLE
HTML Files recognized as Django template in VS Code

### ISSUE THREAD

**Issue by cdrrr** [vscode-django/vscode-django#33]
If Django extension is installed in VS Code, all HTML files are recognized as Django files and displays a wrong icon.

![image](https://user-images.githubusercontent.com/49124845/55291168-1fa3fb00-53e4-11e9-89f6-e4510bb10fd9.png)

**Comment by dustinmichels** [comment]
I am having problems with this, too.

Configuring the "file.associations" settings seems like the right approach, but even when I add the suggested snippet to my settings, all HTML files get recognized as "django-html."

```json
"files.associations": {
    "**/templates/*.html": "django-html",
    "**/templates/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements"
},
```

Shouldn't this snippet cause only html files in a `templates/` folder to be recognized as "django-html"? Am I missing something?

**Comment by dustinmichels** [comment]
*Update:* These settings seem to work for my needs.

```json
  "files.associations": {
    "*.html": "html",
    "**/templates/**/*.html": "django-html"
  },
```

Would this be a better configuration to include in the README?

**Comment by washie254** [comment]
> _Update:_ These settings seem to work for my needs.
> 
> ```json
>   "files.associations": {
>     "*.html": "html",
>     "**/templates/**/*.html": "django-html"
>   },
> ```
> 
> Would this be a better configuration to include in the README?

This Totally worked for me.

**Comment by Networkqueen** [comment]
Thank you so much this worked for me

**Comment by Ritik-Creates** [comment]
Thanks.... I was getting messed up in my server due to this

**Comment by PianoHallvard** [comment]
Excellent! This has bugged me for months
I just uninstalled django

**Comment by antonygatua** [comment]
Thanks works for me too!

**Comment by Bishwas-py** [comment]
I want this problem in my VSCODE. How to get this problem, please?

**Comment by enricoreich** [comment]
So, after vscode is recognizing django templates as django templates, how do I get all the html and emmet feature back? I mean features like html intellisense, code completion and formatting etc...

for formatting I tried in settings.json:
```json
"[django-html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  }
```
but it does not work. I don't want to install additional extensions like beautify or prettier because they don't support django templates and are making formatting even worse. But it would be enough for me to get IntelliSense and code completion back. Thanks!

**Comment by AlessandroCF** [comment]
Thank you for your very valuable advice, it helped me a lot.
Best regards

**Comment by optimistic-zia** [comment]
I thought at last i got the answer.BUT,
"files.associations" comes up when i search it in settings but,  ' **edit in settings.json** ' option is not present for this one.

**Comment by Pixelshot** [comment]
> I thought at last i got the answer.BUT,
> "files.associations" comes up when i search it in settings but, ' **edit in settings.json** ' option is not present for this one.
> It just shows:
> ![image](https://user-images.githubusercontent.com/62305889/95672523-18f06980-0bbf-11eb-8a1f-57e93942021b.png)



You can insert them individually as below

![Screenshot 2020-11-15 230057](https://user-images.githubusercontent.com/13567265/99188397-ae6eb280-2796-11eb-8155-ee59ca79ebf7.png)

**Comment by sommelon** [comment]
> So, after vscode is recognizing django templates as django templates, how do I get all the html and emmet feature back? I mean features like html intellisense, code completion and formatting etc...
> 
> for formatting I tried in settings.json:
> 
> ```json
> "[django-html]": {
>     "editor.defaultFormatter": "vscode.html-language-features"
>   }
> ```
> 
> but it does not work. I don't want to install additional extensions like beautify or prettier because they don't support django templates and are making formatting even worse. But it would be enough for me to get IntelliSense and code completion back. Any ideas? Thanks!

I would also like to know how to configure the formatting. Right now, I have made a macro with the [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) and [Change Language](https://marketplace.visualstudio.com/items?itemName=usernamehw.change-language-mode) extensions.
I am using this config:
```
"macros.list": {
        "format": [
            {
                "command": "changeLanguageMode.change",
                "args": "html"
            },
            "editor.action.formatDocument",
            {
                "command": "changeLanguageMode.change",
                "args": "django-html"
            },
        ]
    }
```
It would be great if there was a better solution to this.

**Comment by eykanal** [comment]
Solved in [this thread](https://github.com/vscode-django/vscode-django/issues/23#issuecomment-560082018). In summary:

1. Install Beautify by HookyQR (to allow modifying file type formatters)
2. Add the following to your user settings file:
```
"beautify.language": {
    "html": [
        "htm", "html", "django-html"
    ]
},
```

**Comment by eriker75** [comment]
Thank you very much

**Comment by VladIftime** [comment]
> So, after vscode is recognizing django templates as django templates, how do I get all the html and emmet feature back? I mean features like html intellisense, code completion and formatting etc...
> 
> for formatting I tried in settings.json:
> 
> ```json
> "[django-html]": {
>     "editor.defaultFormatter": "vscode.html-language-features"
>   }
> ```
> 
> but it does not work. I don't want to install additional extensions like beautify or prettier because they don't support Django templates and are making formatting even worse. But it would be enough for me to get IntelliSense and code completion back. Any ideas? Thanks!

I found that you have to add the following line to VSCode's settings.json:
`"emmet.includeLanguages": {"django-html": "html"}`

This fixed it for me, hope it helps.

**Comment by fedepuleio** [comment]
> > I thought at last i got the answer.BUT,
> > "files.associations" comes up when i search it in settings but, ' **edit in settings.json** ' option is not present for this one.
> > It just shows:
> > ![image](https://user-images.githubusercontent.com/62305889/95672523-18f06980-0bbf-11eb-8a1f-57e93942021b.png)
> 
> You can insert them individually as below
> 
> ![Screenshot 2020-11-15 230057](https://user-images.githubusercontent.com/13567265/99188397-ae6eb280-2796-11eb-8155-ee59ca79ebf7.png)

you made my day, THANKS!!!!

**Comment by TanvirSalehin** [comment]
> _Update:_ These settings seem to work for my needs.
> 
> ```json
>   "files.associations": {
>     "*.html": "html",
>     "**/templates/**/*.html": "django-html"
>   },
> ```
> 
> Would this be a better configuration to include in the README?

This worked for me... Thanks a lot.

**Comment by Fate1405** [comment]
`
*.html
`
`
**/templates/**/*.html
`

In case you were too lazy to type it out lmao.

**Comment by Seek4samurai** [comment]
> _Update:_ These settings seem to work for my needs.
> 
> ```json
>   "files.associations": {
>     "*.html": "html",
>     "**/templates/**/*.html": "django-html"
>   },
> ```
> 
> Would this be a better configuration to include in the README?

This is the perfect solution. Hands down.

**Comment by sammanamgain** [comment]
just uninstall Django in extension problem solved

**Comment by batisteo** [comment]
Thanks for your patience. I found the undocumented `filenamePatterns` key (see [commit](https://github.com/vscode-django/vscode-django/commit/150cf000533ac66715b15bedae4b501480a24e71)) and it should work as expected now.

:wastebasket:  You can remove the file associations in your settings, for both `django-html` and `html`, as this extensions shouldn’t be that eager with HTML files.

I hope it will reduce the frustration of you guys and new comers.

**Comment by michael-hll** [comment]
> > _Update:_ These settings seem to work for my needs.
> > ```json
> >   "files.associations": {
> >     "*.html": "html",
> >     "**/templates/**/*.html": "django-html"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would this be a better configuration to include in the README?
> 
> This worked for me... Thanks a lot.

This worked for me... Thanks a lot.

**Comment by batisteo** [comment]
@michael-hll Have you updated the extension and tried to remove the html file associations?

**Comment by DanSiGo** [comment]
> _Update:_ These settings seem to work for my needs.
> 
> ```json
>   "files.associations": {
>     "*.html": "html",
>     "**/templates/**/*.html": "django-html"
>   },
> ```
> 
> Would this be a better configuration to include in the README?

this worked for me, but wrote "**/templates/**/*.html": "html" instead

don't know why to use "django-html", but didn't get intellisense with it

**Comment by vedika-gupta** [comment]
> > _Update:_ These settings seem to work for my needs.
> > ```json
> >   "files.associations": {
> >     "*.html": "html",
> >     "**/templates/**/*.html": "django-html"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would this be a better configuration to include in the README?
> 
> This Totally worked for me. -> in case you're lost
> 
> 1. access settings use Ctrl+,
> 2. search file.association on the search bar
> 3. select ' edit in settings.json '
> 4. append  this section in "files.associations":
> 
> > ```
> >  "*.html": "html",
> > "**/templates/**/*.html": "django-html"
> > ```



> > _Update:_ These settings seem to work for my needs.
> > ```json
> >   "files.associations": {
> >     "*.html": "html",
> >     "**/templates/**/*.html": "django-html"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would this be a better configuration to include in the README?
> 
> This Totally worked for me. -> in case you're lost
> 
> 1. access settings use Ctrl+,
> 2. search file.association on the search bar
> 3. select ' edit in settings.json '
> 4. append  this section in "files.associations":
> 
> > ```
> >  "*.html": "html",
> > "**/templates/**/*.html": "django-html"
> > ```

Hey! This worked for me but I am still not able to use doctype file using shift + 1.
