### ISSUE TITLE
Missing or extra spaces in tags breaks syntax highlighting

### ISSUE THREAD

**Issue by henribru** [vscode-django/vscode-django#36]
A tag like `{%if foo%}` or `{%      if foo     %}` is valid syntax, but it's not highlighted at all.

Edit: Github's collapsing my spaces, but the second example is supposed to show additional spaces inbetween the percentage symbols and the tag content.

**Comment by coolchevy** [comment]
Need to fix it. I'm totally agree with the @henribru . Same bug for me
