### ISSUE TITLE
Instructions for Setup include `code .` ?

### ISSUE THREAD

**Issue by adaminfinitum** [vscode-django/vscode-django#45]
In the instructions for setup it says:
```
git clone https//github.com/vscode-django/vscode-django
cd vscode-django
npm install
code .
```
I understand the `.` means "in this directory"  but what is the `code` command?

When I tried it all I got was `bash: code: command not found` and `brew search code` doesn't return an exact match.

**Comment by batisteo** [comment]
Hi! `code` is the binary name for **VS Code** itself. Make sure you have it installed.  
Those lines are for developing this extensions. Is it that what you intended to do?

**Comment by adaminfinitum** [comment]
No, I just wanted to install the extension so that my Django project would have appropriate syntax highlighting and completion suggestions.

It's been a long time since I have used Microsoft products so I'm feeling a bit foolish for not understanding what I'm seeing (like in the instructions for this).

Thanks for your help.

**Comment by batisteo** [comment]
You just have to click the install button inside of VS Code :wink: 
https://code.visualstudio.com/docs/editor/extension-gallery#_install-an-extension

On a side note, I’m not affiliated with Microsoft, and most of the extensions are created by independents developers.
