### ISSUE TITLE
Breaks Emmet

### ISSUE THREAD

**Issue by ruszabarov** [vscode-django/vscode-django#46]
Issue Type: <b>Bug</b>

1. Install the extension
2. Put "emmet.includeLanguages": {"django-html": "html"} in the User Settings file
3. Make sure that the HTML file is using Django-HTML

Extension version: 0.20.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cseder** [comment]
@RuslanZab How about looking into the source-code, maybe you can fix it yourself and create a PR for it, instead of down-voting the plugin on Marketplace. You seem to be qualified at least.
Give some take some, no?

@batisteo Maybe consider mentioning this in the README, so people don't include it as an Emmet language and go all apeshit, until you find someone who can contribute?

**Comment by asdfractal** [comment]
I use Windows and Emmet and this breaks Emmet for me. I usually create divs by typing `.class-name` or an element with `h1.class-name` and this functionality is completely removed. Confirmed by uninstalling the extension and it immediately works again.

I am a student and just started learning django, this extension looks really useful but convenience of Emmet is not worth it. I'm sure there is a way to have both working but I am not experienced enough to know how.

**Comment by jartaud** [comment]
Yep, Emmet stop working after installing this ext. I'm on Ubuntu 20 box.

**Comment by stellarbeam** [comment]
I found this [answer](https://stackoverflow.com/a/55790599/11389917) on StackOverflow. The fix worked for me.
