### ISSUE TITLE
[Syntax] HTML and Django tags not seen as indentable blocks

### ISSUE THREAD

**Issue by batisteo** [vscode-django/vscode-django#5]
Pressing <kbd>Enter</kbd> in a `html` tag:
```html
<div>|</div>
```

```html
<div>
····|
</div>
```

Pressing <kbd>Enter</kbd> in a `django-html` tag:
```html
<div>|</div>
```

```html
<div>
|</div>
```

**Comment by batisteo** [comment]
https://github.com/Microsoft/vscode/issues/55088

**Comment by Sakib-Ahmad-Siddiquee** [comment]
This issue solves a little bit by editing the setting file in Vs-code.
Adding this:

"emmet.preferences": {
        "format.forceIndentationForTags": [
            "body","a","abbr","acronym","abbr","address","applet","embed","object","area","article","aside","audio","b","base","basefont","bdi","bdo","big","blockquote","body","br","button","canvas","caption","center","cite","code","col","colgroup","data","datalist","dd","del","details","dfn","dialog","dir","ul","div","dl","dt","em","embed","fieldset","figcaption","figure","font","footer","form","frame","frameset","h1","h6","head","header","hr","html","i","iframe","img","input","ins","kbd","label","legend","li","link","main","map","mark","meta","meter","nav","noframes","noscript","object","ol","optgroup","option","output","p","param","picture","pre","progress","q","rp","rt","ruby","s","samp","script","section","select","small","source","span","strike","del","s","strong","style","sub","summary","sup","svg","table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track","tt","u","ul","var","video","wbr"
        ]
    },
