### ISSUE TITLE
django html intellisense does not work

### ISSUE THREAD

**Issue by S8s8Max** [vscode-django/vscode-django#53]
<p><strong>
In a normal html file, code suggestion works when i type "cla", but when i type same thing in a django html file, it does not work.
</strong></p>

<br />

<p><strong>
How can i fix this problem?
</strong></p>

<img width="390" alt="スクリーンショット 2020-08-01 14 55 55" src="https://user-images.githubusercontent.com/58761811/89095304-994c5e80-d407-11ea-8378-03c4df0dbebf.png">
<img width="382" alt="スクリーンショット 2020-08-01 14 56 41" src="https://user-images.githubusercontent.com/58761811/89095306-9b162200-d407-11ea-8260-5c9d71bfe2d3.png">
<img width="498" alt="スクリーンショット 2020-08-01 15 05 18" src="https://user-images.githubusercontent.com/58761811/89095398-6c4c7b80-d408-11ea-97aa-9d6149cef89f.png">

**Comment by ianfitzpatrick** [comment]
@S8s8Max Hi, there are many issues open for this already. Only one workaround so far :(

https://github.com/vscode-django/vscode-django/issues/52

**Comment by S8s8Max** [comment]
@ianfitzpatrick Thank you :)
