### ISSUE TITLE
Add syntax highlighting for *.po files

### ISSUE THREAD

**Issue by fgrimau** [vscode-django/vscode-django#55]
## Feature request

The Django language files are a bit hard to read when translating a website. Maybe you could add syntax highlighting in *.po* files.

**Comment by batisteo** [comment]
I’ll modify the README to advise using the [gettext](https://marketplace.visualstudio.com/items?itemName=mrorz.language-gettext) extension. Would it work for you?

**Comment by batisteo** [comment]
Fixed by #879e864

**Comment by fgrimau** [comment]
Sure it would ! Thanks for this quick answer :)
