### ISSUE TITLE
Support "go to definition" for django contrib and installed app base templates

### ISSUE THREAD

**Issue by smcoll** [vscode-django/vscode-django#56]
It seems that CTRL+click or F12 works on `include` or `extends` blocks when the base template is in the current project, but not when the base template is in a `django.contrib` or third-party package.  Would be ideal to support the latter cases.

**Comment by smcoll** [comment]
i don't know what i did differently, but it's working now...

**Comment by tutuca** [comment]
It's not working for me. I think it was working when I used djaneiro. Is this case supported?
