### ISSUE TITLE
Add formatter feature

### ISSUE THREAD

**Issue by Vignesh-Ganesan-008** [vscode-django/vscode-django#66]
This extension is great, I love it. It would be nice if there is a formatter.

**Comment by batisteo** [comment]
For the Python files you could use Black or any formatter supported by the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

Are you suggesting formatter for the Django HTML templates?

**Comment by Vignesh-Ganesan-008** [comment]
Yes

**Comment by eykanal** [comment]
Solved in [this thread](https://github.com/vscode-django/vscode-django/issues/23#issuecomment-560082018). In summary:

1. Install Beautify by HookyQR (to allow modifying file type formatters)
2. Add the following to your user settings file:
```
"beautify.language": {
    "html": [
        "htm", "html", "django-html"
    ]
},
```

**Comment by eykanal** [comment]
Also, duplicate of #51, #33, #23

**Comment by Vignesh-Ganesan-008** [comment]
Thank you, this is really helpful. Much appreciated!
