### ISSUE TITLE
Formatting error for ID tag Django-HTML

### ISSUE THREAD

**Issue by miles-1** [vscode-django/vscode-django#72]
I'm following along with the [django tutorial](https://docs.djangoproject.com/en/3.1/intro/tutorial04/#write-a-minimal-form) and noticed that there's a formatting failure for the `id` tag. Below, you can see that the value of the `id` tag is treated as a string literal even though it uses as a variable in double brackets. The variable in double brackets and quotes in the `value` tag has no such problem. Changing the `id` tag to anything else allows for variable recognition by the formatting rules.

![Screen Shot 2021-02-28 at 4 55 07 PM](https://user-images.githubusercontent.com/56459616/109438132-b79e2b00-79e5-11eb-9e0d-9521a9532f17.png)

**Comment by batisteo** [comment]
Fixed by 3b08e85.

Thanks for letting me know!
