### ISSUE TITLE
is that .env folder required or just a leftover?

### ISSUE THREAD

**Issue by mh-firouzjaah** [vscode-django/vscode-django#73]
hi, I had checked my vscode .extensions folder in the past and also today and it seems that the vscode-django had a big change in size!, so I checked the folder and found a `.env` folder I just cut&paste that folder to another directory and the extension is still working so I want to know if it's required or not?

**Comment by batisteo** [comment]
I will check it, I wasn't aware of it. I will try to remove it from distribution.

**Comment by mh-firouzjaah** [comment]
thank you for your attention

**Comment by batisteo** [comment]
Fixed in d0b44ff
