### ISSUE TITLE
Syntax glitches

### ISSUE THREAD

**Issue by batisteo** [vscode-django/vscode-django#8]
Keyword `is` is not highlighted:
![screenshot from 2018-06-25 11-51-03](https://user-images.githubusercontent.com/2727048/41843548-16310c18-786e-11e8-987a-a75e4bf51d94.png)

Operator `comma` is not parsed correctly:
![screenshot from 2018-06-25 11-51-30](https://user-images.githubusercontent.com/2727048/41843589-2fe72da4-786e-11e8-8c2e-bea612a246f2.png)

In `django-txt`, include is not parsed correctly:
![screenshot from 2018-06-25 11-53-22](https://user-images.githubusercontent.com/2727048/41843730-929e1034-786e-11e8-90c2-98e2b3ca6838.png)

**Comment by batisteo** [comment]
@ajitid Are they other fixes you would like to see in the syntax?

**Comment by batisteo** [comment]
Ping @dragon-lex, as you might be interested as well.

**Comment by ajitid** [comment]
I'm not using Django anymore, sorry!

**Comment by batisteo** [comment]
Fixed by fedbe70

**Comment by ajitid** [comment]
Will open up a new issue if I find any.
