### ISSUE TITLE
Django extenstion prevents html tags appear

### ISSUE THREAD

**Issue by BlackEagle1983** [vscode-django/vscode-django#93]
Hello . I have installed this extension and I have configured my vscode setting.json same as extension's description but when I want to use html snippets in django template only django tags and filters appear. I can change language mode to HTML and again to Django Html to use html snippets and django snippets together but when I restart my editor problem backs . 
@batisteo 
vscode 1.62.3

**Comment by batisteo** [comment]
This seems like a duplicate of #16.
Please reopen if you disagree.
