### ISSUE TITLE
Commenting HTML adds incorect syntax

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [vscode-django/vscode-django#96]
Django became installed with the Python Extension Pack.  I discovered it also took ownership of my HTML files, which is fine, except I have noticed it broke VSCode's `Toggle Line Comment` command.

For example, I pressed the keyboard shortcut `Ctrl + /` and notice how it uses incorrect HTML syntax to surround this HTML line:

```html
{% comment %} <h1>{{task.task_name}}</h1> {% endcomment %}
```
Of course, it should have done this:
```html
<!-- <h1>{{task.task_name}}</h1> -->
```
How do I tell Django to enter the correct comment characters for HTML?

_Update: I just discovered this only seems to be a problem when I'm working with Remote SSH files. Should this be tracked in the Remote SSH issues list or here?_

**Comment by LiveFreeAndRoam** [comment]
>

**Comment by LiveFreeAndRoam** [comment]
Oh, I think the issue was that the HTML file I was editing happened to live in a `templates` folder, which overlaps with the `"files.associations"` settings.

I'll keep an eye on this, but it's probably a non-issue.  The side-effect of installing the Python extension pack causing HTML files to be owned by Django is what caught me out here.

**Comment by jackie1santana** [comment]
disable `Django Template`  from your vscode extensions & do a window reload..

**Comment by MarufMobin** [comment]
i am face same issue then it's now well you need to go first settings.json file then 
"files.associations": {
    "*.html": "html",
  }, 
  
  added "*.html" : "html" -> this line then everything will be fine
